---
title: "sensitivity_analysis"
author: "Hugo Milan"
date: "February 26, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# ANABHT - ANAlytical solver for steady-state BioHeat Transfer problems in 1D
# 
# Copyright (C) 2018 by Cornell University. All Rights Reserved.
# 
# Written by Hugo Fernando Maia Milan.
# 
# Free for educational, research and non-profit purposes.
# Refer to the license file for details.
#
# 
# File:   sensitivity_analysis.rmd
# Author: Hugo Fernando Maia Milan
# Email:  hugofernando@gmail.com
#
# Created on April 15, 2018.
#
#
# Function description:
# Performs the sensitivity analysis
#

print("load libraries")
library(gdata)
library(pbapply)
library(h2o)
library(foreach)
library(doMC)
library(pbmcapply)
library(foreign) # read.octave

setwd("~/OneDrive/Cornell/Publications/2018/Piglets 2013/code/V05/R/ML_training/Best ML models")
h2o.init()
```

```{r}
# loading models
GLM_Ta_brooder = h2o.loadModel("GLM_Ta_brooder_all")
RF_Ta_brooder = h2o.loadModel("RF_Ta_brooder_all")
GBM_Ta_brooder = h2o.loadModel("GBM_Ta_brooder_all")
DL_Ta_brooder = h2o.loadModel("DL_Ta_brooder_all")

GLM_Tg_brooder = h2o.loadModel("GLM_Tg_brooder_all")
RF_Tg_brooder = h2o.loadModel("RF_Tg_brooder_all")
GBM_Tg_brooder = h2o.loadModel("GBM_Tg_brooder_all")
DL_Tg_brooder = h2o.loadModel("DL_Tg_brooder_all")

GLM_Tr = h2o.loadModel("GLM_Tr_all")
RF_Tr = h2o.loadModel("RF_Tr_all")
GBM_Tr = h2o.loadModel("GBM_Tr_all")
DL_Tr = h2o.loadModel("DL_Tr_all")

GLM_Tg_brooder_Ta_pen = h2o.loadModel("GLM_Tg_brooder_Ta_pen_all")
RF_Tg_brooder_Ta_pen = h2o.loadModel("RF_Tg_brooder_Ta_pen_all")
GBM_Tg_brooder_Ta_pen = h2o.loadModel("GBM_Tg_brooder_Ta_pen_all")
DL_Tg_brooder_Ta_pen = h2o.loadModel("DL_Tg_brooder_Ta_pen_all")

GLM_Tr_Ta_pen = h2o.loadModel("GLM_Tr_Ta_pen_all")
RF_Tr_Ta_pen = h2o.loadModel("RF_Tr_Ta_pen_all")
GBM_Tr_Ta_pen = h2o.loadModel("GBM_Tr_Ta_pen_all")
DL_Tr_Ta_pen = h2o.loadModel("DL_Tr_Ta_pen_all")

GLM_Tr_Ta_brooder = h2o.loadModel("GLM_Tr_Ta_brooder_all")
RF_Tr_Ta_brooder = h2o.loadModel("RF_Tr_Ta_brooder_all")
GBM_Tr_Ta_brooder = h2o.loadModel("GBM_Tr_Ta_brooder_all")
DL_Tr_Ta_brooder = h2o.loadModel("DL_Tr_Ta_brooder_all")

# loading LM models
load("../LM/LM_models_new.RData")
# loading full data
data_piglets = read.csv("../../../datasets/data_piglets.csv")
data_piglets_training = read.octave("../../../datasets/trainingPosition.mat") 
data_piglets_training = as.vector(data_piglets_training$trainingPosition)
data_piglets_testing = read.octave("../../../datasets/testingPosition.mat") 
data_piglets_testing = as.vector(data_piglets_testing$testingPosition)
all.dataset = data_piglets[c(data_piglets_training, data_piglets_testing),] # nrow(train.dataset) # 130
# data for ploting boxes
Ta_pen_min = min(all.dataset$Ta_pen)
Ta_pen_max = max(all.dataset$Ta_pen)

Ta_brooder_min = min(all.dataset$Ta_brooder)
Ta_brooder_max = max(all.dataset$Ta_brooder)

Tg_brooder_min = min(all.dataset$Tg_brooder)
Tg_brooder_max = max(all.dataset$Tg_brooder)

heat_power_min = min(all.dataset$Heat_source_power)
heat_power_max = max(all.dataset$Heat_source_power)
```


```{r}
best_models = read.csv("../MSE_best_dataset_all.csv")
color.training = "tomato4"
color.CV = "springgreen4"
color.testing = "royalblue3"

color.barplot = c(color.training, color.CV, color.testing,
                  color.training, color.CV, color.testing,
                  color.training, color.CV, color.testing,
                  color.training, color.CV, color.testing,
                  color.training, color.CV, color.testing)


# Ta_brooder
positions.ploting = 1:5
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), ylim = c(0,3), col = color.barplot)

par(xpd = T)
legend(3, 3.4, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)


# Tg_brooder
positions.ploting = 6:10
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), ylim = c(0,0.62), col = color.barplot)

par(xpd = T)
legend(3.1, 0.76, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)




# Tr
positions.ploting = 11:15
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), col = color.barplot, ylim = c(0, 0.4))

par(xpd = T)
legend(3, 0.47, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)


# Tg_brooder_Ta_pen
positions.ploting = 16:20
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), ylim = c(0,2.5), col = color.barplot)

par(xpd = T)
legend(3, 3.0, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)




# Tr_Ta_pen
positions.ploting = 21:25
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), col = color.barplot, ylim = c(0, 0.4))

par(xpd = T)
legend(2.97, 0.475, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)




# Tr_Ta_brooder
positions.ploting = 26:30
barData = barplot(t(matrix(c(best_models$MSE_training[positions.ploting], best_models$MSE_CV[positions.ploting], best_models$MSE_testing[positions.ploting]), nrow = 5, byrow = F)), beside = T, ylab = expression(paste("Mean squared error ("^{o},"C" ^{2}, ")", sep = "")), cex=1.6, cex.axis = 1.4, cex.lab = 1.6, mgp=c(2.1,0.7,0), names.arg = c("LM", "GLM", "RF", "GBM", "DL"), col = color.barplot, ylim = c(0, 0.4))

par(xpd = T)
legend(2.97, 0.475, c("Training", "CV", "Testing"), pch = 15, cex = 1.4, col = c(color.training, color.CV, color.testing), horiz = T)
par(xpd = F)




```

```{r}
# doing sensitivity analysis
library("plot3D")

Ta_pen_change = seq(10, 30, 0.1)
Ta_brooder_change = seq(10, 40, 0.1)
Tg_brooder_change = seq(10, 40, 0.1)
heat_change = seq(0, 500, 1)

Ta_pen_and_heat_change = data.frame(Ta_pen = rep(Ta_pen_change, times = length(heat_change)),
                                    Heat_source_power = rep(heat_change, each = length(Ta_pen_change)))
Ta_pen_and_heat_change.h2o = as.h2o(Ta_pen_and_heat_change)

Ta_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                    Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
Ta_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_and_heat_change)

Ta_brooder_equal_to_Tg_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                                            Tg_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                    Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
Ta_brooder_equal_to_Tg_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_equal_to_Tg_brooder_and_heat_change)

# Investigating the models for predicting air temperature inside the brooder
LM.Ta_brooder_changes = predict(LM.Ta_brooder_final_all, Ta_pen_and_heat_change)
LM_Ta_brooder_changes.matrix = matrix(  as.vector(LM.Ta_brooder_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(LM_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)


GLM_Ta_brooder_changes = h2o.predict(GLM_Ta_brooder, Ta_pen_and_heat_change.h2o)
GLM_Ta_brooder_changes.matrix = matrix(  as.vector(GLM_Ta_brooder_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GLM_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

RF_Ta_brooder_changes = h2o.predict(RF_Ta_brooder, Ta_pen_and_heat_change.h2o)
RF_Ta_brooder_changes.matrix = matrix(  as.vector(RF_Ta_brooder_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(RF_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

GBM_Ta_brooder_changes = h2o.predict(GBM_Ta_brooder, Ta_pen_and_heat_change.h2o)
GBM_Ta_brooder_changes.matrix = matrix(  as.vector(GBM_Ta_brooder_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GBM_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

DL_Ta_brooder_changes = h2o.predict(DL_Ta_brooder, Ta_pen_and_heat_change.h2o)
DL_Ta_brooder_changes.matrix = matrix(  as.vector(DL_Ta_brooder_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(DL_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)






# Investigating the models for predicting black globe temperature inside the brooder
LM.Tg_brooder_changes = predict(LM.Tg_brooder_final_all, Ta_brooder_and_heat_change)
LM_Tg_brooder_changes.matrix = matrix(  as.vector(LM.Tg_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(LM_Tg_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GLM_Tg_brooder_changes = h2o.predict(GLM_Tg_brooder, Ta_brooder_and_heat_change.h2o)
GLM_Tg_brooder_changes.matrix = matrix(  as.vector(GLM_Tg_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GLM_Tg_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

RF_Tg_brooder_changes = h2o.predict(RF_Tg_brooder, Ta_brooder_and_heat_change.h2o)
RF_Tg_brooder_changes.matrix = matrix(  as.vector(RF_Tg_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(RF_Tg_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GBM_Tg_brooder_changes = h2o.predict(GBM_Tg_brooder, Ta_brooder_and_heat_change.h2o)
GBM_Tg_brooder_changes.matrix = matrix(  as.vector(GBM_Tg_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GBM_Tg_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

DL_Tg_brooder_changes = h2o.predict(DL_Tg_brooder, Ta_brooder_and_heat_change.h2o)
DL_Tg_brooder_changes.matrix = matrix(  as.vector(DL_Tg_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(DL_Tg_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)






# Investigating the models for predicting rectal temperature
LM.Tr_changes = predict(LM.Tr_final_all, Ta_brooder_equal_to_Tg_brooder_and_heat_change)
LM_Tr_changes.matrix = matrix(  as.vector(LM.Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(LM_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GLM_Tr_changes = h2o.predict(GLM_Tr, Ta_brooder_equal_to_Tg_brooder_and_heat_change.h2o)
GLM_Tr_changes.matrix = matrix(  as.vector(GLM_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GLM_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

RF_Tr_changes = h2o.predict(RF_Tr, Ta_brooder_equal_to_Tg_brooder_and_heat_change.h2o)
RF_Tr_changes.matrix = matrix(  as.vector(RF_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(RF_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GBM_Tr_changes = h2o.predict(GBM_Tr, Ta_brooder_equal_to_Tg_brooder_and_heat_change.h2o)
GBM_Tr_changes.matrix = matrix(  as.vector(GBM_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GBM_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

DL_Tr_changes = h2o.predict(DL_Tr, Ta_brooder_equal_to_Tg_brooder_and_heat_change.h2o)
DL_Tr_changes.matrix = matrix(  as.vector(DL_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(DL_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)






# Investigating the models for predicting black globe temperature inside the brooder given air temperature inside the pen
LM.Tg_brooder_Ta_pen_changes = predict(LM.Tg_brooder_Ta_pen_final_all, Ta_pen_and_heat_change)
LM_Tg_brooder_Ta_pen_changes.matrix = matrix(  as.vector(LM.Tg_brooder_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(LM_Tg_brooder_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

GLM_Tg_brooder_Ta_pen_changes = h2o.predict(GLM_Tg_brooder_Ta_pen, Ta_pen_and_heat_change.h2o)
GLM_Tg_brooder_Ta_pen_changes.matrix = matrix(  as.vector(GLM_Tg_brooder_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GLM_Tg_brooder_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

RF_Tg_brooder_Ta_pen_changes = h2o.predict(RF_Tg_brooder_Ta_pen, Ta_pen_and_heat_change.h2o)
RF_Tg_brooder_Ta_pen_changes.matrix = matrix(  as.vector(RF_Tg_brooder_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(RF_Tg_brooder_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

GBM_Tg_brooder_Ta_pen_changes = h2o.predict(GBM_Tg_brooder_Ta_pen, Ta_pen_and_heat_change.h2o)
GBM_Tg_brooder_Ta_pen_changes.matrix = matrix(  as.vector(GBM_Tg_brooder_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GBM_Tg_brooder_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

DL_Tg_brooder_Ta_pen_changes = h2o.predict(DL_Tg_brooder_Ta_pen, Ta_pen_and_heat_change.h2o)
DL_Tg_brooder_Ta_pen_changes.matrix = matrix(  as.vector(DL_Tg_brooder_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(DL_Tg_brooder_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)






# Investigating the models for predicting rectal temperature given air temperature inside the pen
LM.Tr_Ta_pen_changes = predict(LM.Tr_Ta_pen_final_all, Ta_pen_and_heat_change)
LM_Tr_Ta_pen_changes.matrix = matrix(  as.vector(LM.Tr_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(LM_Tr_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

GLM_Tr_Ta_pen_changes = h2o.predict(GLM_Tr_Ta_pen, Ta_pen_and_heat_change.h2o)
GLM_Tr_Ta_pen_changes.matrix = matrix(  as.vector(GLM_Tr_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GLM_Tr_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

RF_Tr_Ta_pen_changes = h2o.predict(RF_Tr_Ta_pen, Ta_pen_and_heat_change.h2o)
RF_Tr_Ta_pen_changes.matrix = matrix(  as.vector(RF_Tr_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(RF_Tr_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

GBM_Tr_Ta_pen_changes = h2o.predict(GBM_Tr_Ta_pen, Ta_pen_and_heat_change.h2o)
GBM_Tr_Ta_pen_changes.matrix = matrix(  as.vector(GBM_Tr_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(GBM_Tr_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)

DL_Tr_Ta_pen_changes = h2o.predict(DL_Tr_Ta_pen, Ta_pen_and_heat_change.h2o)
DL_Tr_Ta_pen_changes.matrix = matrix(  as.vector(DL_Tr_Ta_pen_changes), ncol = length(Ta_pen_change), byrow = T)
image2D(DL_Tr_Ta_pen_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_pen_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature in the pen ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_pen_min, heat_power_max, Ta_pen_max, lty = 2, lwd = 3)






# Investigating the models for predicting rectal temperature given the air temperature inside the brooder
LM.Tr_Ta_brooder_changes = predict(LM.Tr_Ta_brooder_final, Ta_brooder_and_heat_change)
LM_Tr_Ta_brooder_changes.matrix = matrix(  as.vector(LM.Tr_Ta_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(LM_Tr_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GLM_Tr_Ta_brooder_changes = h2o.predict(GLM_Tr_Ta_brooder, Ta_brooder_and_heat_change.h2o)
GLM_Tr_Ta_brooder_changes.matrix = matrix(  as.vector(GLM_Tr_Ta_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GLM_Tr_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

RF_Tr_Ta_brooder_changes = h2o.predict(RF_Tr_Ta_brooder, Ta_brooder_and_heat_change.h2o)
RF_Tr_Ta_brooder_changes.matrix = matrix(  as.vector(RF_Tr_Ta_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(RF_Tr_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

GBM_Tr_Ta_brooder_changes = h2o.predict(GBM_Tr_Ta_brooder, Ta_brooder_and_heat_change.h2o)
GBM_Tr_Ta_brooder_changes.matrix = matrix(  as.vector(GBM_Tr_Ta_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(GBM_Tr_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)

DL_Tr_Ta_brooder_changes = h2o.predict(DL_Tr_Ta_brooder, Ta_brooder_and_heat_change.h2o)
DL_Tr_Ta_brooder_changes.matrix = matrix(  as.vector(DL_Tr_Ta_brooder_changes), ncol = length(Ta_brooder_change), byrow = T)
image2D(DL_Tr_Ta_brooder_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
        colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
        xlab = "Supplemental heat (W)", 
        ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")), 
        mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)


```

```{r}
library("plot3D")
# Creating a video of changing Ta_brooder, Tg_brooder, and Heat_source_power
Ta_brooder_change = seq(10, 40, 0.1)
Tg_brooder_change = seq(10, 40, 0.1)
heat_change = seq(0, 500, 1)

# generating movie for GLM Tr
png("Plots/GLM_Tr_change/GLM_Tr%03d.png")
for (Tg_i in Tg_brooder_change){
  # creating the dataset
  Ta_brooder_fixed_Tg_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                                           Tg_brooder = Tg_i,
                                                           Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
  Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_fixed_Tg_brooder_and_heat_change)
  
  GLM_Tr_changes = h2o.predict(GLM_Tr, Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o)
  GLM_Tr_changes.matrix = matrix(  as.vector(GLM_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
  image2D(GLM_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
          colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
          xlab = "Supplemental heat (W)", 
          ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
          mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
  rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)
  par(xpd = T)
  text(0, 42, pos = 4, bquote("T"["g"] == .(Tg_i) ~ "°C"), cex = 1.6 )
  text(180, 42, pos = 4, bquote("Measured T"["g"] == "[" * .( round(Tg_brooder_min, 1) ) * "," ~ .( round(Tg_brooder_max, 1) ) * "]" ~ "°C"), cex = 1.6 )
  par(xpd = F)
  
  print(Tg_i)
}
dev.off()
# system("ffmpeg -r 30 -i Plots/GLM_Tr_change/GLM_Tr%03d.png -vcodec mpeg4 -b 10M Plots/GLM_Tr_change/GLM_Tr.avi") # may not work in Windows/Mac


# generating movie for RF Tr
png("Plots/RF_Tr_change/RF_Tr%03d.png")
for (Tg_i in Tg_brooder_change){
  # creating the dataset
  Ta_brooder_fixed_Tg_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                                           Tg_brooder = Tg_i,
                                                           Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
  Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_fixed_Tg_brooder_and_heat_change)
  
  RF_Tr_changes = h2o.predict(RF_Tr, Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o)
  RF_Tr_changes.matrix = matrix(  as.vector(RF_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
  image2D(RF_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
          colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
          xlab = "Supplemental heat (W)", 
          ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
          mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
  rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)
  par(xpd = T)
  text(0, 42, pos = 4, bquote("T"["g"] == .(Tg_i) ~ "°C"), cex = 1.6 )
  text(180, 42, pos = 4, bquote("Measured T"["g"] == "[" * .( round(Tg_brooder_min, 1) ) * "," ~ .( round(Tg_brooder_max, 1) ) * "]" ~ "°C"), cex = 1.6 )
  par(xpd = F)
  
  print(Tg_i)
}
dev.off()
# system("ffmpeg -r 30 -i Plots/RF_Tr_change/RF_Tr%03d.png -vcodec mpeg4 -b 10M Plots/RF_Tr_change/RF_Tr.avi") # may not work in Windows/Mac


# generating movie for GBM Tr
png("Plots/GBM_Tr_change/GBM_Tr%03d.png")
for (Tg_i in Tg_brooder_change){
  # creating the dataset
  Ta_brooder_fixed_Tg_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                                           Tg_brooder = Tg_i,
                                                           Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
  Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_fixed_Tg_brooder_and_heat_change)
  
  GBM_Tr_changes = h2o.predict(GBM_Tr, Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o)
  GBM_Tr_changes.matrix = matrix(  as.vector(GBM_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
  image2D(GBM_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
          colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
          xlab = "Supplemental heat (W)", 
          ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
          mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
  rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)
  par(xpd = T)
  text(0, 42, pos = 4, bquote("T"["g"] == .(Tg_i) ~ "°C"), cex = 1.6 )
  text(180, 42, pos = 4, bquote("Measured T"["g"] == "[" * .( round(Tg_brooder_min, 1) ) * "," ~ .( round(Tg_brooder_max, 1) ) * "]" ~ "°C"), cex = 1.6 )
  par(xpd = F)
  
  print(Tg_i)
}
dev.off()
# system("ffmpeg -r 30 -i Plots/GBM_Tr_change/GBM_Tr%03d.png -vcodec mpeg4 -b 10M Plots/GBM_Tr_change/GBM_Tr.avi") # may not work in Windows/Mac


# generating movie for DL Tr
png("Plots/DL_Tr_change/DL_Tr%03d.png")
for (Tg_i in Tg_brooder_change){
  # creating the dataset
  Ta_brooder_fixed_Tg_brooder_and_heat_change = data.frame(Ta_brooder = rep(Ta_brooder_change, times = length(heat_change)),
                                                           Tg_brooder = Tg_i,
                                                           Heat_source_power = rep(heat_change, each = length(Ta_brooder_change)))
  Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o = as.h2o(Ta_brooder_fixed_Tg_brooder_and_heat_change)
  
  DL_Tr_changes = h2o.predict(DL_Tr, Ta_brooder_fixed_Tg_brooder_and_heat_change.h2o)
  DL_Tr_changes.matrix = matrix(  as.vector(DL_Tr_changes), ncol = length(Ta_brooder_change), byrow = T)
  image2D(DL_Tr_changes.matrix, contour = list( labcex = 1.6, lwd = 4, vfont = c("sans serif", "bold italic")), 
          colkey = FALSE, x = heat_change, y = Ta_brooder_change, 
          xlab = "Supplemental heat (W)", 
          ylab = expression(paste("Air temperature inside the brooder ("^{o},"C)", sep = "")),
          mgp=c(2.3,0.7,0), cex.axis = 1.4, cex.lab = 1.6)
  rect(heat_power_min, Ta_brooder_min, heat_power_max, Ta_brooder_max, lty = 2, lwd = 3)
  par(xpd = T)
  text(0, 42, pos = 4, bquote("T"["g"] == .(Tg_i) ~ "°C"), cex = 1.6 )
  text(180, 42, pos = 4, bquote("Measured T"["g"] == "[" * .( round(Tg_brooder_min, 1) ) * "," ~ .( round(Tg_brooder_max, 1) ) * "]" ~ "°C"), cex = 1.6 )
  par(xpd = F)
  
  print(Tg_i)
}
dev.off()
# system("ffmpeg -r 30 -i Plots/DL_Tr_change/DL_Tr%03d.png -vcodec mpeg4 -b 10M Plots/DL_Tr_change/DL_Tr.avi") # may not work in Windows/Mac
```



```{r}
# plot for mean temperatures and predictions
mean.dataset = read.csv("../../../datasets/mean_values.csv")
stderr.dataset = read.csv("../../../datasets/stderr_piglets.csv")

mean.dataset.h2o = as.h2o(mean.dataset)

mean_Ta_brooder_predictions = predict(LM.Ta_brooder_final_all, mean.dataset)
mean_Tg_brooder_predictions = predict(LM.Tg_brooder_final_all, mean.dataset)
mean_Tr_predictions = h2o.predict(DL_Tr, mean.dataset.h2o)


# Ploting mean values +- Stderr
hours.plot = c(1, 2, 3, 4,   6, 7, 8, 9,   11, 12, 13, 14,   16, 17, 18, 19,   21, 22, 23, 24)
Ta_brooder.color = "springgreen4"
Tg_brooder.color = "royalblue3"
Tr.color = "tomato4"

measured.symbol = 16
predicted.symbol = 15
symbol.size = 1.3

################## Ploting for all (Ta_brooder, Tg_brooder, and Tr)
par(mar = c(5, 4, 4.5, 2) + 0.1)
plot(hours.plot, mean.dataset$Ta_brooder, xlim = c(1,24), ylim=c(19, 39), xaxt = "n", col = Ta_brooder.color, pch = measured.symbol, ylab = expression(paste("Temperature ("^{o},"C)", sep = "")), xlab = "Time (hour)", mgp=c(2.3,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)
# including ticks
# axis(2, at = c(18:30), labels = FALSE)
# power_source = 0
axis(1, at = c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 60
axis(1, at = 5+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 5+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 100
axis(1, at = 10+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 10+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 160
axis(1, at = 15+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 15+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 200
axis(1, at = 20+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 20+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)

# grid lines
abline(h = 20, untf = FALSE, lty = 3, col = "gray")
abline(h = 25, untf = FALSE, lty = 3, col = "gray")
abline(h = 30, untf = FALSE, lty = 3, col = "gray")
abline(h = 35, untf = FALSE, lty = 3, col = "gray")

points(hours.plot, mean.dataset$Ta_brooder, col = Ta_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Ta_brooder - stderr.dataset$Ta_brooder, hours.plot, mean.dataset$Ta_brooder + stderr.dataset$Ta_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Ta_brooder.color)

points(hours.plot, mean_Ta_brooder_predictions, col = Ta_brooder.color, pch = predicted.symbol, cex=symbol.size)

# Tg_brooder
points(hours.plot, mean.dataset$Tg_brooder, col = Tg_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tg_brooder - stderr.dataset$Tg_brooder, hours.plot, mean.dataset$Tg_brooder + stderr.dataset$Tg_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tg_brooder.color)

points(hours.plot, mean_Tg_brooder_predictions, col = Tg_brooder.color, pch = predicted.symbol, cex=symbol.size)


# Tr
points(hours.plot, mean.dataset$Tr, col = Tr.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tr - stderr.dataset$Tr, hours.plot, mean.dataset$Tr + stderr.dataset$Tr, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tr.color)

points(hours.plot, as.vector(mean_Tr_predictions), col = Tr.color, pch = predicted.symbol, cex=symbol.size)

# separation lines
abline(v=5, untf = FALSE, lty = 3)
abline(v=10, untf = FALSE, lty = 3)
abline(v=15, untf = FALSE, lty = 3)
abline(v=20, untf = FALSE, lty = 3)

# writing power
par(xpd = TRUE)
text(x = 2.5, y = 40.8, "0 W", cex = 1.6)
text(x = 2.5+5, y = 40.8, "60 W", cex = 1.6)
text(x = 2.5+10, y = 40.8, "100 W", cex = 1.6)
text(x = 2.5+15, y = 40.8, "160 W", cex = 1.6)
text(x = 2.5+20, y = 40.8, "200 W", cex = 1.6)

# Legend
legend(0.5, 36, c(expression(paste('T'["a"], " (LM)", sep="")), expression(paste('T'["g"], " (LM)", sep="")), expression(paste('T'["r"], " (DL)", sep=""))), col = c(Ta_brooder.color, Tg_brooder.color, Tr.color), lty = c(1, 1, 1), lwd = 2,  pch = c(NA, NA, NA), pt.cex = symbol.size, cex = 1.6, horiz = T)
par(xpd = FALSE, mar = c(5, 4, 4, 2) + 0.1)

################# Ploting for Ta_brooder and Tg_brooder
par(mar = c(5, 4, 4.5, 2) + 0.1)
plot(hours.plot, mean.dataset$Ta_brooder, xlim = c(1,24), ylim=c(19, 30), xaxt = "n", col = Ta_brooder.color, pch = measured.symbol, ylab = expression(paste("Temperature ("^{o},"C)", sep = "")), xlab = "Time (hour)", mgp=c(2.3,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)
# including ticks
# axis(2, at = c(18:30), labels = FALSE)
# power_source = 0
axis(1, at = c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 60
axis(1, at = 5+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 5+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 100
axis(1, at = 10+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 10+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 160
axis(1, at = 15+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 15+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 200
axis(1, at = 20+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 20+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)

# grid lines
abline(h = 20, untf = FALSE, lty = 3, col = "gray")
abline(h = 22, untf = FALSE, lty = 3, col = "gray")
abline(h = 24, untf = FALSE, lty = 3, col = "gray")
abline(h = 26, untf = FALSE, lty = 3, col = "gray")
abline(h = 28, untf = FALSE, lty = 3, col = "gray")
abline(h = 30, untf = FALSE, lty = 3, col = "gray")

points(hours.plot, mean.dataset$Ta_brooder, col = Ta_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Ta_brooder - stderr.dataset$Ta_brooder, hours.plot, mean.dataset$Ta_brooder + stderr.dataset$Ta_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Ta_brooder.color)

points(hours.plot, mean_Ta_brooder_predictions, col = Ta_brooder.color, pch = predicted.symbol, cex=symbol.size)

# Tg_brooder
points(hours.plot, mean.dataset$Tg_brooder, col = Tg_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tg_brooder - stderr.dataset$Tg_brooder, hours.plot, mean.dataset$Tg_brooder + stderr.dataset$Tg_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tg_brooder.color)

points(hours.plot, mean_Tg_brooder_predictions, col = Tg_brooder.color, pch = predicted.symbol, cex=symbol.size)

# separation lines
abline(v=5, untf = FALSE, lty = 3)
abline(v=10, untf = FALSE, lty = 3)
abline(v=15, untf = FALSE, lty = 3)
abline(v=20, untf = FALSE, lty = 3)

# writing power
par(xpd = TRUE)
text(x = 2.5, y = 31, "0 W", cex = 1.6)
text(x = 2.5+5, y = 31, "60 W", cex = 1.6)
text(x = 2.5+10, y = 31, "100 W", cex = 1.6)
text(x = 2.5+15, y = 31, "160 W", cex = 1.6)
text(x = 2.5+20, y = 31, "200 W", cex = 1.6)

# Legend
legend(16, 24, c(expression(paste('T'["a"], " (LM)", sep="")), expression(paste('T'["g"], " (LM)", sep=""))), col = c(Ta_brooder.color, Tg_brooder.color), lty = c(1, 1), lwd = 2,  pch = c(NA, NA), pt.cex = symbol.size, cex = 1.6)
par(xpd = FALSE, mar = c(5, 4, 4, 2) + 0.1)

# describe symbols for measured and predicted in the text



################################ Plot for Tr
par(mar = c(5, 4, 4.5, 2) + 0.1)
plot(hours.plot, mean.dataset$Tr, xlim = c(1,24), ylim=c(36.5, 39), xaxt = "n", col = Tr.color, pch = measured.symbol, ylab = expression(paste("Temperature ("^{o},"C)", sep = "")), xlab = "Time (hour)", mgp=c(2.3,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)
# including ticks
# axis(2, at = c(18:30), labels = FALSE)
# power_source = 0
axis(1, at = c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 60
axis(1, at = 5+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 5+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 100
axis(1, at = 10+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 10+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 160
axis(1, at = 15+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 15+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 200
axis(1, at = 20+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 20+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)

# grid lines
abline(h = 36.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 37, untf = FALSE, lty = 3, col = "gray")
abline(h = 37.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 38, untf = FALSE, lty = 3, col = "gray")
abline(h = 38.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 39, untf = FALSE, lty = 3, col = "gray")

# Tr
points(hours.plot, mean.dataset$Tr, col = Tr.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tr - stderr.dataset$Tr, hours.plot, mean.dataset$Tr + stderr.dataset$Tr, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tr.color)

points(hours.plot, as.vector(mean_Tr_predictions), col = Tr.color, pch = predicted.symbol, cex=symbol.size)

# separation lines
abline(v=5, untf = FALSE, lty = 3)
abline(v=10, untf = FALSE, lty = 3)
abline(v=15, untf = FALSE, lty = 3)
abline(v=20, untf = FALSE, lty = 3)

# writing power
par(xpd = TRUE)
text(x = 2.5, y = 39.2, "0 W", cex = 1.6)
text(x = 2.5+5, y = 39.2, "60 W", cex = 1.6)
text(x = 2.5+10, y = 39.2, "100 W", cex = 1.6)
text(x = 2.5+15, y = 39.2, "160 W", cex = 1.6)
text(x = 2.5+20, y = 39.2, "200 W", cex = 1.6)
```

```{r}
# ploting mean percentage errors
mean.dataset = read.csv("../../../datasets/mean_values.csv")
stderr.dataset = read.csv("../../../datasets/stderr_piglets.csv")

mean.dataset.h2o = as.h2o(mean.dataset)

mean_Ta_brooder_predictions = predict(LM.Ta_brooder_final_all, mean.dataset)
mean_Ta_brooder_percentage_error = mean(abs(mean_Ta_brooder_predictions - mean.dataset$Ta_brooder)/mean.dataset$Ta_brooder*100)
sem_Ta_brooder_percentage_error = sd(abs(mean_Ta_brooder_predictions - mean.dataset$Ta_brooder)/mean.dataset$Ta_brooder*100)/sqrt(nrow(mean.dataset) - 1)


mean_Tg_brooder_predictions = predict(LM.Tg_brooder_final_all, mean.dataset)
mean_Tg_brooder_percentage_error = mean(abs(mean_Tg_brooder_predictions - mean.dataset$Tg_brooder)/mean.dataset$Tg_brooder*100)
sem_Tg_brooder_percentage_error = sd(abs(mean_Tg_brooder_predictions - mean.dataset$Tg_brooder)/mean.dataset$Tg_brooder*100)/sqrt(nrow(mean.dataset) - 1)

mean_Tr_predictions = as.vector(h2o.predict(DL_Tr, mean.dataset.h2o))
mean_Tr_percentage_error = mean(abs(mean_Tr_predictions - mean.dataset$Tr)/mean.dataset$Tr*100)
sem_Tr_percentage_error = sd(abs(mean_Tr_predictions - mean.dataset$Tr)/mean.dataset$Tr*100)/sqrt(nrow(mean.dataset) - 1)

Ta_brooder.color = "springgreen4"
Tg_brooder.color = "royalblue3"
Tr.color = "tomato4"

Ta_brooder.symbol = 17
Tg_brooder.symbol = 15
Tr.symbol = 16

plot.positions = c(1, 2, 3)
plot.symbols = c(Ta_brooder.symbol, Tg_brooder.symbol, Tr.symbol)
plot.colors = c(Ta_brooder.color, Tg_brooder.color, Tr.color)
symbol.size = 1.4


plot(plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error), xlim = c(1,3), ylim=c(0.5, 2), xaxt = "n", col = plot.colors, pch = plot.symbols, ylab = expression(paste("Percentage error (%)", sep = "")), xlab = "", mgp=c(2.3,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)

# grid lines
abline(h = 0.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 0.75, untf = FALSE, lty = 3, col = "gray")
abline(h = 1, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.25, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.75, untf = FALSE, lty = 3, col = "gray")
abline(h = 2, untf = FALSE, lty = 3, col = "gray")

arrows(plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error) - c(sem_Ta_brooder_percentage_error, sem_Tg_brooder_percentage_error, sem_Tr_percentage_error), plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error) + c(sem_Ta_brooder_percentage_error, sem_Tg_brooder_percentage_error, sem_Tr_percentage_error), lwd = 2, angle = 90, code = 3, length = 0.05, col = plot.colors)

legend(2.05, 2, c(expression(paste('T'["a"], " (LM)", sep="")), expression(paste('T'["g"], " (LM)", sep="")), expression(paste('T'["r"], " (DL)", sep=""))), col = plot.colors, lwd = 2,  pch = plot.symbols, pt.cex = symbol.size, cex = 1.6)
```



```{r}
# plot for mean temperatures and predictions when only Ta_pen is given
mean.dataset = read.csv("../../../datasets/mean_values.csv")
stderr.dataset = read.csv("../../../datasets/stderr_piglets.csv")

mean.dataset.h2o = as.h2o(mean.dataset)

mean_Ta_brooder_predictions = predict(LM.Ta_brooder_final_all, mean.dataset)
mean_Tg_brooder_predictions = predict(LM.Tg_brooder_Ta_pen_final_all, mean.dataset)
mean_Tr_predictions = predict(LM.Tr_RE_only_final, mean_piglets, re.form = NA)


# Ploting mean values +- Stderr
hours.plot = c(1, 2, 3, 4,   6, 7, 8, 9,   11, 12, 13, 14,   16, 17, 18, 19,   21, 22, 23, 24)
Ta_brooder.color = "springgreen4"
Tg_brooder.color = "royalblue3"
Tr.color = "tomato4"

measured.symbol = 16
predicted.symbol = 15
symbol.size = 1.3

# export as 552 x 479
################## Ploting for all (Ta_brooder, Tg_brooder, and Tr)
par(mar = c(5, 4, 4.5, 2) + 0.1)
plot(hours.plot, mean.dataset$Ta_brooder, xlim = c(1,24), ylim=c(19, 39), xaxt = "n", col = Ta_brooder.color, pch = measured.symbol, ylab = expression(paste("Temperature ("^{o},"C)", sep = "")), xlab = "Time (hour)", mgp=c(2.3,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)
# including ticks
# axis(2, at = c(18:30), labels = FALSE)
# power_source = 0
axis(1, at = c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 60
axis(1, at = 5+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 5+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 100
axis(1, at = 10+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 10+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 160
axis(1, at = 15+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 15+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)
# power_source = 200
axis(1, at = 20+c(4, 5, 6, 7) - 3, labels = c(4, 5, 6, 7), cex.axis = 1.4)
axis(1, at = 20+c(5, 7) - 3, labels = c(5, 7), cex.axis = 1.4, tick = FALSE)

# grid lines
abline(h = 20, untf = FALSE, lty = 3, col = "gray")
abline(h = 25, untf = FALSE, lty = 3, col = "gray")
abline(h = 30, untf = FALSE, lty = 3, col = "gray")
abline(h = 35, untf = FALSE, lty = 3, col = "gray")

points(hours.plot, mean.dataset$Ta_brooder, col = Ta_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Ta_brooder - stderr.dataset$Ta_brooder, hours.plot, mean.dataset$Ta_brooder + stderr.dataset$Ta_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Ta_brooder.color)

points(hours.plot, mean_Ta_brooder_predictions, col = Ta_brooder.color, pch = predicted.symbol, cex=symbol.size)

# Tg_brooder
points(hours.plot, mean.dataset$Tg_brooder, col = Tg_brooder.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tg_brooder - stderr.dataset$Tg_brooder, hours.plot, mean.dataset$Tg_brooder + stderr.dataset$Tg_brooder, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tg_brooder.color)

points(hours.plot, mean_Tg_brooder_predictions, col = Tg_brooder.color, pch = predicted.symbol, cex=symbol.size)


# Tr
points(hours.plot, mean.dataset$Tr, col = Tr.color, pch = measured.symbol, cex=symbol.size)
arrows(hours.plot, mean.dataset$Tr - stderr.dataset$Tr, hours.plot, mean.dataset$Tr + stderr.dataset$Tr, lwd = 1.5, angle = 90, code = 3, length = 0.05, col = Tr.color)

points(hours.plot, as.vector(mean_Tr_predictions), col = Tr.color, pch = predicted.symbol, cex=symbol.size)

# separation lines
abline(v=5, untf = FALSE, lty = 3)
abline(v=10, untf = FALSE, lty = 3)
abline(v=15, untf = FALSE, lty = 3)
abline(v=20, untf = FALSE, lty = 3)

# writing power
par(xpd = TRUE)
text(x = 2.5, y = 40.8, "0 W", cex = 1.6)
text(x = 2.5+5, y = 40.8, "60 W", cex = 1.6)
text(x = 2.5+10, y = 40.8, "100 W", cex = 1.6)
text(x = 2.5+15, y = 40.8, "160 W", cex = 1.6)
text(x = 2.5+20, y = 40.8, "200 W", cex = 1.6)
par(xpd = FALSE, mar = c(5, 4, 4, 2) + 0.1)

# Legend
legend(0, 36, c(expression(paste('T'["a"], " (LM)", sep="")), expression(paste('T'["g"], " (LM)", sep="")), expression(paste('T'["r"], " (LM)", sep=""))), col = c(Ta_brooder.color, Tg_brooder.color, Tr.color), lty = c(1, 1, 1), lwd = 2,  pch = c(NA, NA, NA), pt.cex = symbol.size, cex = 1.6, horiz = T, x.intersp = 0.3)
```

```{r}
# ploting mean percentage errors
mean.dataset = read.csv("../../../datasets/mean_values.csv")
stderr.dataset = read.csv("../../../datasets/stderr_piglets.csv")

mean.dataset.h2o = as.h2o(mean.dataset)

mean_Ta_brooder_predictions = predict(LM.Ta_brooder_final_all, mean.dataset)
mean_Ta_brooder_percentage_error = mean(abs(mean_Ta_brooder_predictions - mean.dataset$Ta_brooder)/mean.dataset$Ta_brooder*100)
sem_Ta_brooder_percentage_error = sd(abs(mean_Ta_brooder_predictions - mean.dataset$Ta_brooder)/mean.dataset$Ta_brooder*100)/sqrt(nrow(mean.dataset) - 1)


mean_Tg_brooder_predictions = predict(LM.Tg_brooder_Ta_pen_final_all, mean.dataset)
mean_Tg_brooder_percentage_error = mean(abs(mean_Tg_brooder_predictions - mean.dataset$Tg_brooder)/mean.dataset$Tg_brooder*100)
sem_Tg_brooder_percentage_error = sd(abs(mean_Tg_brooder_predictions - mean.dataset$Tg_brooder)/mean.dataset$Tg_brooder*100)/sqrt(nrow(mean.dataset) - 1)

mean_Tr_predictions = predict(LM.Tr_RE_only_final, mean_piglets, re.form = NA)
mean_Tr_percentage_error = mean(abs(mean_Tr_predictions - mean.dataset$Tr)/mean.dataset$Tr*100)
sem_Tr_percentage_error = sd(abs(mean_Tr_predictions - mean.dataset$Tr)/mean.dataset$Tr*100)/sqrt(nrow(mean.dataset) - 1)

Ta_brooder.color = "springgreen4"
Tg_brooder.color = "royalblue3"
Tr.color = "tomato4"

Ta_brooder.symbol = 17
Tg_brooder.symbol = 15
Tr.symbol = 16

plot.positions = c(1, 2, 3)
plot.symbols = c(Ta_brooder.symbol, Tg_brooder.symbol, Tr.symbol)
plot.colors = c(Ta_brooder.color, Tg_brooder.color, Tr.color)
symbol.size = 1.4

# export as 312 x 479
plot(plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error), xlim = c(1,3), ylim=c(0.5, 2), xaxt = "n", col = plot.colors, pch = plot.symbols, ylab = expression(paste("Percentage error (%)", sep = "")), xlab = "", mgp=c(1.5,0.7,0), cex=symbol.size, cex.axis = 1.4, cex.lab = 1.6)

# grid lines
abline(h = 0.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 0.75, untf = FALSE, lty = 3, col = "gray")
abline(h = 1, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.25, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.5, untf = FALSE, lty = 3, col = "gray")
abline(h = 1.75, untf = FALSE, lty = 3, col = "gray")
abline(h = 2, untf = FALSE, lty = 3, col = "gray")

arrows(plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error) - c(sem_Ta_brooder_percentage_error, sem_Tg_brooder_percentage_error, sem_Tr_percentage_error), plot.positions, c(mean_Ta_brooder_percentage_error, mean_Tg_brooder_percentage_error, mean_Tr_percentage_error) + c(sem_Ta_brooder_percentage_error, sem_Tg_brooder_percentage_error, sem_Tr_percentage_error), lwd = 2, angle = 90, code = 3, length = 0.05, col = plot.colors)

legend("topright", c(expression(paste('T'["a"], " (LM)", sep="")), expression(paste('T'["g"], " (LM)", sep="")), expression(paste('T'["r"], " (LM)", sep=""))), col = plot.colors, lwd = 2,  pch = plot.symbols, pt.cex = symbol.size, cex = 1.6)
```
