---
title: "data_analysis"
author: "Hugo Milan"
date: "February 16, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ANABHT - ANAlytical solver for steady-state BioHeat Transfer problems in 1D
# 
# Copyright (C) 2018 by Cornell University. All Rights Reserved.
# 
# Written by Hugo Fernando Maia Milan.
# 
# Free for educational, research and non-profit purposes.
# Refer to the license file for details.
#
# 
# File:   FD_size.rmd
# Author: Hugo Fernando Maia Milan
# Email:  hugofernando@gmail.com
#
# Created on May 9, 2018.
#
#
# Function description:
# Plots the finite difference size validation test
#

# loading data
# Set the directory to where this file is located
FDsize = read.table("../../datasets/HairCoatDivision_1_100dataTrainingKM.csv")
colnames(FDsize) = c("Nodes", 
                     "Ts_min", "Ts_mean", "Ts_max",
                     "qs_min", "qs_mean", "qs_max", 
                     "Th_min", "Th_mean", "Th_max",
                     "Time")

# size 643 x 499
Ts.color = "darkslategray"
Th.color = "firebrick1"

min.line = 2
mean.line = 1
max.line = 3

minTaxis = 28
maxTaxis = 38

par(mar = c(4, 4, 4, 4))
plot(FDsize$Nodes, FDsize$Ts_min, type = 'l', ylim = c(minTaxis, maxTaxis), col = Ts.color, lty = min.line, yaxs = "i",
     ylab = expression(paste("Temperature ("^{o},"C)", sep = "")), mgp=c(2.3,0.7,0), xlab = "Number of sublayers", cex.axis = 1.4, cex.lab = 1.6, lwd = 3)

grid()
lines(FDsize$Nodes, FDsize$Ts_min, col = Ts.color, lty = min.line, lwd = 3)
lines(FDsize$Nodes, FDsize$Ts_mean, col = Ts.color, lty = mean.line, lwd = 3)
lines(FDsize$Nodes, FDsize$Ts_max, col = Ts.color, lty = max.line, lwd = 3)

lines(FDsize$Nodes, FDsize$Th_min, col = Th.color, lty = min.line, lwd = 3)
lines(FDsize$Nodes, FDsize$Th_mean, col = Th.color, lty = mean.line, lwd = 3)
lines(FDsize$Nodes, FDsize$Th_max, col = Th.color, lty = max.line, lwd = 3)

par(new = T)
plot(FDsize$Nodes, FDsize$Time, type = 'l', bty = "n", axes = F, ylim = c(0, 350), yaxs = "i",
     ylab = "", mgp=c(2.3,0.7,0), xlab = "", cex.axis = 1.4, cex.lab = 1.6, lwd = 3)
axis(4, at = seq(0, 350, 70),  cex.axis = 1.4)
mtext("Time (s)", side = 4, cex = 1.6, line=2.5)

arrows(63, 85, 50, 100, lwd = 3)
text(63, 85, "Time", cex = 1.6, pos = 4)

par(xpd = T)
legend(-18, 425, c(expression("T"["s"]), expression("T"["h"]), "min", "mean", "max"), pch = c(15, 15, NA, NA, NA), cex = 1.4,
       col = c(Ts.color, Th.color, "black", "black", "black"), 
       lty = c(NA, NA, min.line, mean.line, max.line),
       lwd = c(NA, NA, 3, 3, 3),
       horiz = T)
par(xpd = F)

# how much does it change between 20 and the last one?
FDsize[20, ] - FDsize[100,]
(FDsize[20, ] - FDsize[100,])/FDsize[100,]*100
```
